#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path("../../lib", __FILE__)

require "delfos"

Delfos.configure { |c| c.application_directories = "." }
Delfos.start!
Delfos.update_distance!
Delfos.finish!
