#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path("../../lib", __FILE__)

require "delfos"

Delfos.setup! application_directories: "."
Delfos.update_distance!
Delfos.finish!
